MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
c_stdlib_version:          # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
