{% set name = "nomad" %}
{% set version = "1.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/hashicorp/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6ecb888fe9a9c5b89cbf5b5587035266ee32e0df0c789f3b0a26825422d855f7
    patches:
      - 0001-Don-t-overwrite-compilers.patch
  - url: https://raw.githubusercontent.com/hashicorp/cronexpr/a5b9ff11e6c27ab08e1dfd6ad1fe99179f441d0a/APLv2
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
    fn: LICENSE-cronexpr
  - url: https://raw.githubusercontent.com/tj/go-spin/721f604c567004b82bb196abe227ab60360184ba/LICENSE
    sha256: e4855d38fa4a5c43945b62f0731836851d055bc200f42631f0854e75fdefe77c
    fn: LICENSE-gospin

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - yarn <2
    - go-licenses

test:
  commands:
    - nomad -h

about:
  home: https://nomadproject.io
  license: BUSL-1.1
  license_file:
    - LICENSE
    - LICENSE-cronexpr
    - LICENSE-gospin
    - license-files/
  summary: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
  doc_url: https://developer.hashicorp.com/nomad/docs
  dev_url: https://github.com/hashicorp/{{ name }}

extra:
  recipe-maintainers:
    - jonashaag
    - xhochy
    - pavelzw
