{% set name = "nomad" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/hashicorp/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c1ec75af7c1b7c1f3db445e6e4041d8da20fe1d94a43e70af45153a21db4a2cc
    patches:
      - 0001-Don-t-overwrite-compilers.patch
  - url: https://raw.githubusercontent.com/hashicorp/cronexpr/a5b9ff11e6c27ab08e1dfd6ad1fe99179f441d0a/APLv2
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
    fn: LICENSE-cronexpr
  - url: https://raw.githubusercontent.com/tj/go-spin/721f604c567004b82bb196abe227ab60360184ba/LICENSE
    sha256: e4855d38fa4a5c43945b62f0731836851d055bc200f42631f0854e75fdefe77c
    fn: LICENSE-gospin

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }}
    - make
    - nodejs 20.*
    - yarn <2
    - go-licenses

test:
  commands:
    - nomad -h

about:
  home: https://nomadproject.io
  license: BUSL-1.1
  license_file:
    - LICENSE
    - LICENSE-cronexpr
    - LICENSE-gospin
    - license-files/
  summary: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
  doc_url: https://developer.hashicorp.com/nomad/docs
  dev_url: https://github.com/hashicorp/{{ name }}

extra:
  recipe-maintainers:
    - jonashaag
    - xhochy
    - pavelzw
